DROP TABLE IF EXISTS TEACHERS_STUDENTS;
DROP TABLE IF EXISTS STUDENTS_TEACHERS;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS TEACHERS;

CREATE TABLE STUDENTS (
 ID          INTEGER     NOT NULL AUTO_INCREMENT,
 FIRST_NAME  VARCHAR(50) NOT NULL,
 LAST_NAME   VARCHAR(50) NOT NULL,
 EMAIL       VARCHAR(100),
 PRIMARY KEY (ID)
);

CREATE TABLE TEACHERS (
 ID          INTEGER     NOT NULL AUTO_INCREMENT,
 FIRST_NAME  VARCHAR(50) NOT NULL,
 LAST_NAME   VARCHAR(50) NOT NULL,
 EMAIL       VARCHAR(100),
 PRIMARY KEY (ID)
);

CREATE TABLE STUDENTS_TEACHERS (
 ID_STUDENTS INTEGER     NOT NULL,
 ID_TEACHERS INTEGER     NOT NULL,
 PRIMARY KEY (ID_STUDENTS, ID_TEACHERS), 
 FOREIGN KEY (ID_STUDENTS) REFERENCES STUDENTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (ID_TEACHERS) REFERENCES TEACHERS(ID) ON DELETE CASCADE
);